<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareLibre [
  <!ELEMENT softwareLibre (programas,licencias)>
  <!ELEMENT licencias (licencia*)>
  <!ELEMENT licencia EMPTY>
  <!ELEMENT programas (programa*)>
  <!ELEMENT programa (nombre,version*)>
  <!ELEMENT version EMPTY>
  <!ELEMENT nombre (#PCDATA)>
  <!ATTLIST licencia nombre NMTOKENS #REQUIRED>
  <!ATTLIST version nombre NMTOKEN #REQUIRED>
  <!ATTLIST version licencia NMTOKENS #REQUIRED>
  <!ATTLIST version fechaPublicación CDATA #IMPLIED>
]>
<softwareLibre>
  <programas>
    <programa>
      <nombre>Inkscape</nombre>
      <version nombre="0.47" licencia="GPL v2" fechaPublicación="17/08/2010" />
      <version nombre="0.48" licencia="GPL v2" fechaPublicación="17/08/2010" />
      <version nombre="0.48.2" licencia="GPL v2" fechaPublicación="14/08/2011" />
    </programa>
    <programa>
      <nombre>PostgreSQL</nombre>
      <version nombre="9.1.0" licencia="BSD2" fechaPublicación="15/09/2011" />
      <version nombre="9.1.3" licencia="BSD2"/>
    </programa>
  </programas>
  <licencias>
    <licencia nombre="GPL v2" />
    <licencia nombre="BSD2" />
    <licencia nombre="Apache v2" />
  </licencias>
</softwareLibre>