=== angelazarquiel/lenguaje-de-marcas/XML/proyectoeclipse.dtd
<!ELEMENT projectDescription (name, comment, projects, buildSpec, natures,linkedResources?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT projects (project*)>
<!ELEMENT project (#PCDATA)>
<!ELEMENT buildSpec (buildCommand*)>
<!ELEMENT buildCommand (name, arguments)>
<!ELEMENT arguments (dictionary?)>
<!ELEMENT dictionary (key, value)*>
<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT natures (nature+)>
<!ELEMENT nature (#PCDATA)>
<!ELEMENT linkedResources (#PCDATA)>

=== angelazarquiel/lenguaje-de-marcas/XML/proyectoUT5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectDescription SYSTEM "proyectoeclipse.dtd">
<projectDescription>
	<name>UT5Clases</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
	</natures>
</projectDescription>
