=== angelazarquiel/lenguaje-de-marcas/XML/XSD/libro2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="isbn" type="xs:long"/>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="autor" type="xs:string"/>
        <xs:element ref="personaje"
               minOccurs="1" maxOccurs="unbounded">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="personaje">
      <xs:complexType>
                 <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="amigos" type="xs:string"/>
                        <xs:element name="calificacion" type="xs:string"
                                           minOccurs="0"/>
                 </xs:sequence>
      </xs:complexType>
  </xs:element>
</xs:schema>

=== angelazarquiel/lenguaje-de-marcas/XML/XSD/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="libro2.xsd">
  <isbn>12345678</isbn>
  <titulo>EL Quijote</titulo>
  <autor>Cervantes</autor>
  <personaje>
    <nombre>El quijote</nombre>
    <amigos>Sancho</amigos>
    <calificacion>extrovertido</calificacion>
  </personaje>
  <personaje>
    <nombre>Sancho</nombre>
    <amigos>El quijote</amigos>
  </personaje>
</libro>
